# Generated by Django 3.1.3 on 2021-05-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBusinessTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_business_test_name', models.CharField(max_length=100, verbose_name='API业务测试名称')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='APIEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_environment_name', models.CharField(max_length=200, verbose_name='API环境名称')),
                ('api_title', models.CharField(max_length=200, verbose_name='API环境标题名称')),
                ('api_environment_describe', models.TextField(default='', null=True, verbose_name='API环境描述')),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='APIModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_module_name', models.CharField(max_length=50, verbose_name='API模块名称')),
                ('api_module_describe', models.TextField(default='', null=True, verbose_name='API模块描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='APIProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_project_name', models.CharField(max_length=50, verbose_name='API项目名称')),
                ('describe', models.TextField(default='', max_length=2000, null=True, verbose_name='描述')),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='APITestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_test_result_name', models.CharField(default='', max_length=200, verbose_name='api测试报告名称')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UIElementsOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elements_operation_name', models.CharField(max_length=500, verbose_name='元素操作名称')),
                ('elements_operation_title', models.CharField(max_length=500, verbose_name='元素操作标题')),
                ('elements_operation_describe', models.TextField(default='', null=True, verbose_name='描述')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UIPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_page_name', models.CharField(max_length=50, verbose_name='UI页面名称')),
                ('ui_page_describe', models.TextField(default='', null=True, verbose_name='UI页面描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='UIPageElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_page_element_name', models.CharField(max_length=100, verbose_name='UI页面元素名称')),
                ('ui_page_element', models.CharField(max_length=600, verbose_name='UI页面元素')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UIPositioning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positioning_name', models.CharField(max_length=50, verbose_name='定位方法名称')),
                ('locating_method', models.CharField(max_length=200, verbose_name='定位方法')),
                ('describe', models.TextField(default='', null=True, verbose_name='描述')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UIProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_project_name', models.CharField(max_length=50, verbose_name='UI项目名称')),
                ('describe', models.TextField(default='', max_length=2000, null=True, verbose_name='描述')),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UITestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_test_case_name', models.CharField(max_length=100, verbose_name='UI测试用例名称')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ui_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.uiproject')),
            ],
        ),
        migrations.CreateModel(
            name='UITestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_test_task_name', models.CharField(default='', max_length=100, verbose_name='UI测试任务名称')),
                ('describe', models.TextField(default='', null=True, verbose_name='描述')),
                ('status', models.IntegerField(default=0, verbose_name='状态：')),
                ('cases', models.TextField(default='', verbose_name='关联UI用例')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ui_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.uiproject')),
            ],
        ),
        migrations.CreateModel(
            name='UITestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_test_result_name', models.CharField(default='', max_length=100, verbose_name='UI测试报告名称')),
                ('error', models.IntegerField(verbose_name='错误用例')),
                ('failure', models.IntegerField(verbose_name='失败用例')),
                ('skipped', models.IntegerField(verbose_name='跳过用例')),
                ('tests', models.IntegerField(verbose_name='总用例数')),
                ('run_time', models.CharField(default='', max_length=200, verbose_name='运行时长')),
                ('result', models.TextField(default='', verbose_name='详细')),
                ('successful', models.IntegerField(verbose_name='成功用例')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ui_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.uitesttask')),
            ],
        ),
        migrations.CreateModel(
            name='UITestCaseAssociated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_operation', models.CharField(max_length=100, verbose_name='元素操作')),
                ('element_input', models.CharField(blank=True, max_length=100, null=True, verbose_name='元素输出')),
                ('x_coordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='X坐标')),
                ('y_coordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='Y坐标')),
                ('waiting_time', models.CharField(max_length=100, verbose_name='等待时间')),
                ('case_steps', models.CharField(max_length=100, verbose_name='操作步骤')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.uitestcase')),
                ('ui_page_elements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.uipageelement')),
            ],
        ),
        migrations.AddField(
            model_name='uipageelement',
            name='ui_element_positioning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.uipositioning'),
        ),
        migrations.AddField(
            model_name='uipageelement',
            name='ui_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.uipage'),
        ),
        migrations.AddField(
            model_name='uipageelement',
            name='ui_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.uiproject'),
        ),
        migrations.AddField(
            model_name='uipage',
            name='ui_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='automated_main.uiproject'),
        ),
        migrations.CreateModel(
            name='APITestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_test_task_name', models.CharField(default='', max_length=100, verbose_name='API测试任务名称')),
                ('describe', models.TextField(default='', null=True, verbose_name='描述')),
                ('status', models.IntegerField(default=0, verbose_name='状态：')),
                ('cases', models.TextField(default='', verbose_name='关联API用例')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('api_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.apiproject')),
            ],
        ),
        migrations.CreateModel(
            name='APITestResultAssociated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_test_case_name', models.CharField(default='', max_length=100, verbose_name='api测试用例名称')),
                ('api_error', models.CharField(blank=True, max_length=100, null=True, verbose_name='失败')),
                ('api_successful', models.CharField(blank=True, max_length=100, null=True, verbose_name='成功')),
                ('abnormal', models.TextField(blank=True, max_length=5000, null=True, verbose_name='异常')),
                ('json_extract_variable_conversion', models.TextField(blank=True, max_length=5000, null=True, verbose_name='json提取变量转换')),
                ('api_assertion_results', models.TextField(blank=True, max_length=5000, null=True, verbose_name='断言结果')),
                ('api_variable_results', models.TextField(blank=True, max_length=5000, null=True, verbose_name='参数提取')),
                ('api_request_results', models.TextField(blank=True, max_length=5000, null=True, verbose_name='API请求结果')),
                ('api_business_test_name', models.TextField(blank=True, max_length=5000, null=True, verbose_name='API业务测试名称')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('api_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.apitestresult')),
                ('api_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.apitesttask')),
            ],
        ),
        migrations.AddField(
            model_name='apitestresult',
            name='api_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.apitesttask'),
        ),
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_test_case_name', models.CharField(max_length=100, verbose_name='API测试用例名称')),
                ('api_method', models.IntegerField(verbose_name='请求方法')),
                ('api_url', models.TextField(verbose_name='API请求地址')),
                ('api_parameter_types', models.IntegerField(verbose_name='参数类型')),
                ('api_headers', models.TextField(verbose_name='请求头')),
                ('api_parameter_body', models.TextField(verbose_name='参数内容')),
                ('api_assert_type', models.IntegerField(verbose_name='断言类型')),
                ('api_assert_text', models.TextField(verbose_name='断言结果')),
                ('api_variable_results', models.CharField(max_length=200, null=True, verbose_name='变量提取结果')),
                ('api_value_variable', models.CharField(max_length=200, null=True, verbose_name='提取变量')),
                ('api_key_variable', models.CharField(max_length=200, null=True, verbose_name='关键字变量名称')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('api_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.apienvironment')),
                ('api_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.apimodule')),
            ],
        ),
        migrations.AddField(
            model_name='apimodule',
            name='api_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='automated_main.apiproject'),
        ),
        migrations.CreateModel(
            name='ApiBusinessTestAssociated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_steps', models.CharField(max_length=100, verbose_name='操作步骤')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('api_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.apimodule')),
                ('api_test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.apitestcase')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.apibusinesstest')),
            ],
        ),
        migrations.AddField(
            model_name='apibusinesstest',
            name='api_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.apiproject'),
        ),
    ]
