# Generated by Django 3.1.3 on 2021-05-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestresult',
            name='api_error_total_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='失败总数'),
        ),
        migrations.AddField(
            model_name='apitestresult',
            name='api_successful_total_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='成功总数'),
        ),
        migrations.AddField(
            model_name='apitestresult',
            name='api_total_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='API总数'),
        ),
    ]
