# Generated by Django 3.1.3 on 2021-05-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_main', '0002_auto_20210510_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitestresultassociated',
            name='api_request_results',
            field=models.JSONField(null=True, verbose_name='API请求结果'),
        ),
    ]
