# Generated by Django 3.1.3 on 2021-05-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_main', '0003_auto_20210510_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitestresultassociated',
            name='api_request_results',
            field=models.JSONField(default=None, null=True, verbose_name='API请求结果'),
        ),
    ]
