# Generated by Django 3.1.3 on 2021-05-27 14:01

import automated_main.models.performance_test.performance_script
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_main', '0004_auto_20210527_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_project_name', models.CharField(max_length=50, verbose_name='性能项目名称')),
                ('describe', models.TextField(default='', max_length=2000, null=True, verbose_name='描述')),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_script_name', models.CharField(max_length=50, verbose_name='性能测试脚本名称')),
                ('performance_script', models.FileField(upload_to=automated_main.models.performance_test.performance_script.upload_to)),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
