# Generated by Django 3.1.3 on 2021-05-27 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automated_main', '0005_performanceproject_performancescript'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancescript',
            name='performance_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='automated_main.performanceproject'),
        ),
    ]
