# Generated by Django 3.1.3 on 2021-06-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_main', '0007_auto_20210602_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancescript',
            name='performance_status',
            field=models.IntegerField(default=0, verbose_name='性能脚本运行状态'),
        ),
    ]
