# Generated by Django 3.1.3 on 2021-06-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automated_main', '0008_performancescript_performance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uitestresult',
            name='skipped',
        ),
        migrations.RemoveField(
            model_name='uitestresult',
            name='tests',
        ),
        migrations.CreateModel(
            name='UITestResultAssociated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_test_case_name', models.CharField(default='', max_length=100, verbose_name='ui测试用例名称')),
                ('ui_error', models.CharField(blank=True, max_length=100, null=True, verbose_name='失败')),
                ('ui_successful', models.CharField(blank=True, max_length=100, null=True, verbose_name='成功')),
                ('abnormal', models.TextField(blank=True, max_length=5000, null=True, verbose_name='异常')),
                ('ui_assertion_results', models.TextField(blank=True, max_length=5000, null=True, verbose_name='断言结果')),
                ('updata_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ui_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.uitestresult')),
                ('ui_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.uitesttask')),
            ],
        ),
    ]
