# Generated by Django 3.1.3 on 2021-07-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_main', '0012_auto_20210707_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestresultassociated',
            name='api_body',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='apitestresultassociated',
            name='api_header',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='header'),
        ),
        migrations.AddField(
            model_name='apitestresultassociated',
            name='api_url',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='请求地址'),
        ),
    ]
