# Generated by Django 3.1.3 on 2021-07-19 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automated_main', '0013_auto_20210707_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitestcase',
            name='api_documentation',
            field=models.TextField(max_length=5000, null=True, verbose_name='API接口文档地址'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='api_key_variable',
            field=models.TextField(max_length=5000, null=True, verbose_name='关键字变量名称'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='api_test_case_name',
            field=models.TextField(max_length=5000, verbose_name='API测试用例名称'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='api_value_variable',
            field=models.TextField(max_length=5000, null=True, verbose_name='提取变量'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='api_variable_results',
            field=models.TextField(max_length=5000, null=True, verbose_name='变量提取结果'),
        ),
        migrations.CreateModel(
            name='ApiParameterExtraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_variable_results', models.TextField(max_length=5000, null=True, verbose_name='变量提取结果')),
                ('api_value_variable', models.TextField(max_length=5000, null=True, verbose_name='提取变量')),
                ('api_key_variable', models.TextField(max_length=5000, null=True, verbose_name='关键字变量名称')),
                ('api_test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_main.apitestcase')),
            ],
        ),
    ]
