# Generated by Django 3.1.3 on 2021-07-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automated_main', '0015_auto_20210720_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uitestcaseassociated',
            name='case_steps',
            field=models.CharField(max_length=100, null=True, verbose_name='操作步骤'),
        ),
        migrations.AlterField(
            model_name='uitestcaseassociated',
            name='ui_page_elements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='automated_main.uipageelement'),
        ),
        migrations.AlterField(
            model_name='uitestcaseassociated',
            name='waiting_time',
            field=models.CharField(max_length=100, null=True, verbose_name='等待时间'),
        ),
    ]
