# Generated by Django 3.1.3 on 2021-08-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_main', '0016_auto_20210722_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitestresult',
            name='ui_test_script',
            field=models.CharField(default='', max_length=1000, verbose_name='UI测试脚本'),
        ),
    ]
