# Generated by Django 3.1.3 on 2021-09-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_main', '0018_auto_20210813_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='uipageelement',
            name='ui_page_element_more',
            field=models.CharField(max_length=600, null=True, verbose_name='UI页面元素-多个'),
        ),
    ]
